local wk = require("which-key")

wk.setup({
	delay = 120,
	notify = false,
})

wk.add({
	{ "<leader>b", group = "buffers" },
	{ "<leader>s", group = "split/screen" },
	{ "<leader>sv", desc = "Split vertical" },
	{ "<leader>sh", desc = "Split horizontal" },
	{ "<leader>sc", desc = "Split close" },
	{ "<leader>so", desc = "Split only" },
	{ "<leader>se", desc = "Split equalize" },
	{ "<leader>sH", desc = "Split resize left" },
	{ "<leader>sJ", desc = "Split resize down" },
	{ "<leader>sK", desc = "Split resize up" },
	{ "<leader>sL", desc = "Split resize right" },
	{ "<leader>f", group = "find/files" },
	{ "<leader>a", group = "actions/file" },
	{ "<leader>as", desc = "Action save" },
	{ "<leader>aa", desc = "Action save as" },
	{ "<leader>am", desc = "Action move file" },
	{ "<leader>ax", desc = "Action chmod +x" },
	{ "<leader>t", group = "test/term" },
	{ "<leader>td", desc = "Todo list" },
	{ "<leader>u", group = "ui" },
	{ "<leader>o", group = "open" },
	{ "<leader>g", group = "git" },
	{ "<leader>gs", desc = "Git status" },
	{ "<leader>gd", desc = "Git diff split" },
	{ "<leader>gD", desc = "Git diffview open" },
	{ "<leader>gb", desc = "Git blame" },
	{ "<leader>gh", desc = "Git file history" },
	{ "<leader>gq", desc = "Git diffview close" },
	{ "<leader>p", group = "plugins" },
	{ "<leader>r", group = "replace/reload" },
	{ "<leader>rr", desc = "Replace all" },
	{ "<leader>rc", desc = "Reload current file" },
	{ "<leader>x", group = "trouble/lists" },
	{ "<leader>xx", desc = "Trouble toggle diagnostics" },
	{ "<leader>xd", desc = "Trouble buffer diagnostics" },
	{ "<leader>xq", desc = "Trouble quickfix list" },
	{ "<leader>xl", desc = "Trouble location list" },
	{ "<leader>z", group = "folds" },
	{ "<leader>zc", desc = "Fold close" },
	{ "<leader>zo", desc = "Fold open" },
	{ "<leader>za", desc = "Fold toggle" },
	{ "<leader>zM", desc = "Fold close all" },
	{ "<leader>zR", desc = "Fold open all" },
	{ "<leader>m", group = "make" },
	{ "<leader>c", group = "code" },
})
